import { readdirSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SPRITE_DIR = join(ROOT, "public", "sprites");
const OUT_DIR = join(ROOT, "lib");
const OUT_FILE = join(OUT_DIR, "pokemon-index.generated.ts");

mkdirSync(OUT_DIR, { recursive: true });

const titleCase = (s) =>
  s
    .split(/[\s-]+/)
    .map((w) => (w.length > 0 ? w[0].toUpperCase() + w.slice(1) : w))
    .join(" ");

const files = readdirSync(SPRITE_DIR)
  .filter((f) => extname(f).toLowerCase() === ".png")
  .sort();

const entries = files.map((file, i) => {
  const slug = basename(file, ".png");
  const displayName = titleCase(slug);
  return { slug, file, displayName, idx: i };
});

const banner = `// AUTO-GENERATED by scripts/generate-index.mjs — do not edit by hand.\n// Run \`npm run index\` to regenerate.\n\n`;

const body = `export interface SpriteEntry {
  slug: string;
  file: string;
  displayName: string;
  idx: number;
}

export const POKEMON_INDEX: readonly SpriteEntry[] = ${JSON.stringify(entries, null, 2)} as const;

export const POKEMON_BY_SLUG: Record<string, SpriteEntry> = Object.fromEntries(
  POKEMON_INDEX.map((p) => [p.slug, p])
);

export const POKEMON_COUNT = POKEMON_INDEX.length;
`;

writeFileSync(OUT_FILE, banner + body, "utf-8");

console.log(`[index] Wrote ${entries.length} entries to ${OUT_FILE}`);
